version: '3.3'

volumes:
  postgres_data:
  static_data:
  media_data:
  redoc:

services:

  db:
    image: postgres:13.0-alpine
    container_name: foodgram-db
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../backend/.env
    ports: 
      - 5432:5432
    restart: always

  backend:
    build: ../backend
    container_name: foodgram_backend
    volumes:
      - static_data:/app/static/
      - media_data:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ../backend/.env
    restart: always


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.24.0-alpine
    container_name: foodgram_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_data:/var/html/static/
      - media_data:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    restart: always
