# Generated by Django 4.2.4 on 2023-09-06 08:59

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0002_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(default=2, help_text='Type cooking time using minutes.', validators=[django.core.validators.MinValueValidator(1, message='Minimum value is 1!'), django.core.validators.MaxValueValidator(1440, message='Maximum value is 1440 (24h)!')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=2, verbose_name='publication date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ingredient name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(max_length=20, verbose_name='unit of measurement'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='recipe author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Write a description', verbose_name='recipe description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='foodgram/images/', verbose_name='meal picture'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='recipe name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True, verbose_name='tag colour'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='tag name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='tag slug'),
        ),
        migrations.CreateModel(
            name='TagsRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_list', to='foodgram.recipe', verbose_name='recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_list', to='foodgram.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'List of tags for recipe',
                'verbose_name_plural': 'List of tags for recipes',
            },
        ),
        migrations.CreateModel(
            name='PurchasingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_list', to='foodgram.recipe', verbose_name='purchasing recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_list', to=settings.AUTH_USER_MODEL, verbose_name='purchasing user')),
            ],
            options={
                'verbose_name': 'Recipe for purchasing',
                'verbose_name_plural': 'Recipes for purchasing',
                'ordering': ('recipe',),
            },
        ),
        migrations.CreateModel(
            name='IngredientsRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimaum value is 1!')], verbose_name='Ingredient quantity')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='foodgram.ingredient', verbose_name='description')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='foodgram.recipe', verbose_name='recipe')),
            ],
            options={
                'verbose_name': 'List of ingredients for recipe',
                'verbose_name_plural': 'List of ingredients for recipes',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='foodgram.recipe', verbose_name='favorite recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite recipe',
                'verbose_name_plural': 'Favorite recipes',
                'ordering': ['-recipe'],
            },
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='foodgram.IngredientsRecipe', to='foodgram.ingredient', verbose_name='recipe ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', through='foodgram.TagsRecipe', to='foodgram.tag', verbose_name='recipe tags'),
        ),
        migrations.AddConstraint(
            model_name='tagsrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_tags_for_recipe'),
        ),
        migrations.AddConstraint(
            model_name='purchasinglist',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_shopping_pair'),
        ),
        migrations.AddConstraint(
            model_name='ingredientsrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredients_for_recipe'),
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_favorite_recipes'),
        ),
    ]
