# Generated by Django 4.2.5 on 2023-09-13 07:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_alter_tag_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units',
            new_name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True, verbose_name='tag colour'),
        ),
    ]
