# Generated by Django 4.2.5 on 2023-09-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_follow_follow_unique_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
