# Generated by Django 4.2.5 on 2023-09-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_favorite_delete_favoriterecipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
